### ISSUE TITLE
Change "let" to "let_expr", "inherit" to "inherit_expr", etc?

### ISSUE THREAD

**Issue by justinwoo** [cstrahan/tree-sitter-nix#2]
My problem with working with the output of this package is that I now have the task of distinguishing between the let node containing children and the "let" literal, i.e..:

```
type let (3 children)
text let apple = 1;

[
  type let (0 children)
  text let
, ...
]
```

Could we change the names of these so that they don't overlap with the literal names?

**Comment by justinwoo** [comment]
In the `if` ambiguity case, it would be easier if expr_if were not private

https://github.com/cstrahan/tree-sitter-nix/blob/6c442630c428b52b1e16ae477effd0ae4ad46245/grammar.js#L94-L99

**Comment by cstrahan** [comment]
To determine the node type, are you using [`const char *ts_node_type(TSNode);`
](https://github.com/tree-sitter/tree-sitter/blob/77636e8fe6418c10a1c2ddb7a278c886bff7ef35/lib/include/tree_sitter/api.h#L114) (or a suitable binding, if using a language other than C/C++)? That should let you know, without any ambiguity I can see, what type of node you're looking at. If I'm missing something, could you help walk me through the problem, please?

**Comment by cstrahan** [comment]
... unless that example you pasted suggests that what tree sitter reports at the type in both cases is just `let`. I'm hoping that's not the case (I haven't had a chance to exercise the parser as part of a program yet).

**Comment by justinwoo** [comment]
It reports them as just 'let' in node tree-sitter, which just wraps the C generation (which is why all generated projects have gyp bindings generated in the root, for node)

**Comment by cstrahan** [comment]
I don't think that's what I'm seeing from my end:

```javascript
$ node
> const Parser = require('tree-sitter');
undefined
> nix = require(".")
Language { name: 'nix' }
> parser = new Parser()
Parser {}
> parser.setLanguage(nix)
Parser { [Symbol(parser.language)]: Language { name: 'nix' } }
> const sourceCode = '[ "let" ]'
undefined
> tree = parser.parse(sourceCode)
Tree { input: '[ "let" ]', getText: [Function: getTextFromString] }
> tree.rootNode
SyntaxNode {
  type: expression,
  startPosition: {row: 0, column: 0},
  endPosition: {row: 0, column: 9},
  childCount: 1,
}
> tree.rootNode.namedChild(0)
SyntaxNode {
  type: list,
  startPosition: {row: 0, column: 0},
  endPosition: {row: 0, column: 9},
  childCount: 3,
}
> tree.rootNode.namedChild(0).namedChild(0)
SyntaxNode {
  type: string,
  startPosition: {row: 0, column: 2},
  endPosition: {row: 0, column: 7},
  childCount: 2,
}
> tree.rootNode.namedChild(0).namedChild(0).type
'string'
```

Could you share a snippet of code that illustrates what you're seeing?

**Comment by justinwoo** [comment]
here's an example: https://github.com/justinwoo/tree-sitter-node-example/blob/3112954653db65e3be4763cbcc2315cf54d9c06f/index.js#L36-L40

**Comment by cstrahan** [comment]
Ah, I see.

The problem arises because your `nodeToObject` function is conflating named children and unnamed children, so when you walk that JSON object you have no way to discern the unnamed `let` token from the named `let` node. If you look at my code above, I use `namedChild(n)` to skip the `[` token nested within the `list` node; if I had used `child(0)`, that wouldn't be the case. Similarly, if you have a `let` node, and you call `child(0)`, you'd get the `let` token nested within, rather than the bindings (or if there are no bindings, the expression body).

You can preserve that info (and avoid the ambiguity when walking) if you change your function like so:

```javascript
function nodeToObject(node) {
  return {
    type: node.type,
    childCount: node.children.length,
    children: node.children.map(x => nodeToObject(x)),
    isNamed: node.isNamed
  };
}
```

Now a `let` token will have `isNamed = false`, and a `let` node will have `isNamed = true`.

Does that help / make sense?

**Comment by justinwoo** [comment]
It's not what I'd like to work with but I could postprocess it anyway then

**Comment by cstrahan** [comment]
My concern with the proposed change is that it makes the the node names rather verbose, while the token itself (which no one really needs to inspect 99% of the time) ironically stays nice and terse. The tree-sitter API is (well, _was_; more on that later) intended to be used by indexing into the named children in this scenario -- which, admittedly, you can't conveniently do if you have a JSON object, unless you first read it into a data structure that discriminates on `isNamed` and provides similar `child`/`unnamedChild`/`namedChild` functions. At that point you're reimplementing much of the logic that you get for free in tree-sitter's C API, so I'm curious why you need to JSONify the tree first.

The Ruby grammar sets a precedent for the "nodes named after their primary token" approach, so I'd like to follow suit for the sake of idiom: https://github.com/tree-sitter/tree-sitter-ruby/blob/50eab3217240cc6c7061f8d5d42a9d211e791bb4/grammar.js#L210-L234

However, there's a change that just landed within the last day that allows you to name the fields within a node, which will provide another unambiguous way to walk the tree, and in practice will probably be more ergonomic than any existing approach: https://github.com/tree-sitter/tree-sitter/pull/271

Anyway, didn't want you think that I was being arbitrary in the naming / being difficult :blush:. I'd certainly be willing to consider other naming changes, because some of it I just pulled out of my butt (e.g. the nix grammar refers to a collection of bindings, like within a `let`, as `binds`; so what to call the individual bindings? `binding`? But then there's the inconsistency of the parent node being named `binds` rather than `bindings` (although I could always deviate from the official grammar...), so maybe just `bind`? :man_shrugging:). I don't want to bike shed a whole bunch, but if enough people think the other names I came up with are unintuitive, I'd certainly entertain some changes.

**Comment by cstrahan** [comment]
I don't know if it makes it all that much better, but you could also do something like:

```javascript
function nodeToObject(node) {
  return {
    type: node.type,
    childCount: node.children.length,
    children: node.children.map(x => nodeToObject(x)),
    namedChildren: node.namedChildren.map(x => nodeToObject(x)),
    unnamedChildren: node.unnamedChildren.map(x => nodeToObject(x)),
    isNamed: node.isNamed
  };
}
```

**Comment by justinwoo** [comment]
One exception I'm now finding is that it's very useful to know if I have a quantity, i.e. `import (fn x) {}`, where only using named children would leave me with a series of `app` going down, so I end up having to figure out if the immediate child is `app` to wrap it in parens or simply `identifier`. from https://github.com/NixOS/nix/blob/f32fbf952d8eb15963da65a162da169de72f36fa/src/libexpr/parser.y#L386

https://github.com/cstrahan/tree-sitter-nix/blob/6c442630c428b52b1e16ae477effd0ae4ad46245/grammar.js#L159

Could this be extracted to `$.quantity` for little cost?
