### ISSUE TITLE
prettier type names

### ISSUE THREAD

**Issue by milahu** [cstrahan/tree-sitter-nix#20]
rename `indented_string` to `stringblock`?

rename `source_expression` to `nixexpr`?

**Comment by cstrahan** [comment]
I pushed some changes in 14af97221e59b355e421f71f94bf302f860267a8.

I tried to stick to the official Nix nomenclature as close as possible, so I'll stick with `indented_string` for now.

Because this is seeing a lot of use from editors for syntax highlighting and such, I've changed `source_expression` to `source_code` and made the top level expression optional, that way when people open an empty buffer they aren't immediately met with errors.

Hopefully that suffices?

**Comment by milahu** [comment]
> made the top level expression optional

thanks : )

> I tried to stick to the official Nix nomenclature

makes sense

> I've changed `source_expression` to `source_code`

in `web-tree-sitter`, the root node is exposed as [tree.rootNode](https://github.com/tree-sitter/tree-sitter/blob/ccd6bf554d922596ce905730d98a77af368bba5c/lib/binding_web/tree-sitter-web.d.ts#L128)
so i would call it `root_node` ... but its arbitrary, `source_code` is good too
