### ISSUE TITLE
parse errors

### ISSUE THREAD

**Issue by milahu** [cstrahan/tree-sitter-nix#21]
maybe only on incremental parsing:

* top-level comments give parse error = input `# s`
* empty input gives parse error

**Comment by cstrahan** [comment]
IIRC, pretty much any way you can feed nix code into any of the `nix` commands requires a valid expression, so depending on how you look at it, you could argue that the empty string (or text only consisting of white space and comments) is not in the language.

But speaking pragmatically (with respect to editors that will otherwise put red squiggles, and similar), maybe it makes sense to amend the grammar to make the top level expression optional.

**Comment by cstrahan** [comment]
Resolved in 14af97221e59b355e421f71f94bf302f860267a8
