### ISSUE TITLE
Interpolation outside strings is parsed incorrectly

### ISSUE THREAD

**Issue by rnhmjoj** [cstrahan/tree-sitter-nix#22]
I just came a cross this code
```nix
{
  slaveIfs = map (i: cfg.interfaces.${i}) (filter (i: cfg.interfaces ? ${i}) slaves);
}
```
that breaks the syntax highlighting in neovim. It seems variable interpolation is only working correctly when inside quoted.

**Comment by cstrahan** [comment]
Thank you for reporting this @rnhmjoj.

The problem was that I treated `?` like a normal binary operator, which takes two expressions as operands. In reality, `?` is supposed to take an attrpath on the right.

I want to keep things sane for statically typed languages, so I decided to break `?` out into a new `has_attr` rule, that way AST types don't have to do something like `Either Expression Attrpath` for the right-hand-side of all binary expressions. I decided to keep the "operator" field though because I figure it might be convenient for dynamically typed languages to be able to branch on that field instead of checking the respective node's type -- and if I'm wrong, I don't think it really hurts anything.

Should be fixed in 267da27715c1cca66534e80452263b5ae4fb2380.
